#!/usr/bin/python

import os
import subprocess
import demon

pidfile = '/var/run/iso8583-forwarder.pid'
if not demon.isLive(pidfile):
    try:
        os.remove(pidfile)
    except OSError:
        pass
    subprocess.call(['/etc/init.d/iso8583-forwarder', 'start'])
